export default {
  title: 'Customers',
  description: 'Central customer registry used across modules.',
  addCustomer: 'Add customer',
  editCustomer: 'Edit customer',
  deleteCustomer: 'Delete',
  searchPlaceholder: 'Search (code, name, VAT, email, phone)…',
  empty: 'No customers yet.',
  columnSettings: 'Visible columns',
  columnSettingsSubtitle: 'Choose which columns you want to see in the table.',
  resetColumns: 'Reset to default',
  saveColumns: 'Save',
  requiredPill: 'Required',
  columnsWidthPlaceholder: 'Width (px/%)',
  columnsResetDone: 'Default columns restored.',
  columnsSaved: 'Columns saved.',
  columnsSaveFailed: 'Saving columns failed.',
  columns: {
    code: 'Code',
    name: 'Name',
    ico: 'Company ID',
    dic: 'VAT ID',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    note: 'Note',
    active: 'Active',
    actions: 'Actions',
  },
  form: {
    code: 'Code',
    name: 'Name *',
    ico: 'Company ID',
    dic: 'VAT ID',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    note: 'Note',
    active: 'Active',
    required: '* required',
    save: 'Save',
    cancel: 'Cancel',
  },
  confirmDelete: 'Are you sure you want to delete this customer?',
  messages: {
    loadFailed: 'Failed to load customers.',
    saveFailed: 'Failed to save customer.',
    deleteFailed: 'Failed to delete customer.',
    saved: 'Customer saved.',
    deleted: 'Customer deleted.',
  },
  pagination: {
    perPage: 'Per page',
    prev: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    emptyInfo: '',
  },
  details: {
    title: 'Customer details',
    edit: 'Edit',
    createdAt: 'Created',
    updatedAt: 'Updated',
  },
};
