export default {
  title: 'Zákazníci',
  description: 'Centrální evidence zákazníků pro využití napříč moduly.',
  addCustomer: 'Přidat zákazníka',
  editCustomer: 'Upravit zákazníka',
  deleteCustomer: 'Smazat',
  searchPlaceholder: 'Hledat (kód, název, IČO, e-mail, telefon)…',
  empty: 'Zatím zde není žádný zákazník.',
  columnSettings: 'Zobrazené sloupce',
  columnSettingsSubtitle: 'Vyberte, které sloupce chcete zobrazit v tabulce.',
  resetColumns: 'Obnovit výchozí',
  saveColumns: 'Uložit',
  requiredPill: 'Povinný',
  columnsWidthPlaceholder: 'Šířka (px/%)',
  columnsResetDone: 'Výchozí sloupce byly obnoveny.',
  columnsSaved: 'Sloupce byly uloženy.',
  columnsSaveFailed: 'Uložení sloupců selhalo.',
  columns: {
    code: 'Kód',
    name: 'Název',
    ico: 'IČO',
    dic: 'DIČ',
    email: 'E-mail',
    phone: 'Telefon',
    address: 'Adresa',
    note: 'Poznámka',
    active: 'Aktivní',
    actions: 'Akce',
  },
  form: {
    code: 'Kód',
    name: 'Název *',
    ico: 'IČO',
    dic: 'DIČ',
    email: 'E-mail',
    phone: 'Telefon',
    address: 'Adresa',
    note: 'Poznámka',
    active: 'Aktivní',
    required: '* povinné pole',
    save: 'Uložit',
    cancel: 'Zrušit',
  },
  confirmDelete: 'Opravdu chcete smazat tohoto zákazníka?',
  messages: {
    loadFailed: 'Nepodařilo se načíst zákazníky.',
    saveFailed: 'Uložení zákazníka se nezdařilo.',
    deleteFailed: 'Smazání zákazníka se nezdařilo.',
    saved: 'Zákazník uložen.',
    deleted: 'Zákazník smazán.',
  },
  pagination: {
    perPage: 'Na stránku',
    prev: 'Předchozí',
    next: 'Další',
    page: 'Strana',
    of: 'z',
    emptyInfo: '',
  },
  details: {
    title: 'Detail zákazníka',
    edit: 'Upravit',
    createdAt: 'Vytvořeno',
    updatedAt: 'Aktualizováno',
  },
};
