export default {
  title: 'CRM výroby nátěrových hmot',
  subtitle: 'Sjednocený pohled na suroviny, polotovary a finální zakázky.',
  materials: 'Suroviny',
  suppliers: 'Dodavatelé',
  intermediates: 'Polotovary',
  recipes: 'Receptury',
  orders: 'Zakázky',
  emptyMaterials: 'Zatím nejsou uloženy žádné suroviny.',
  emptyIntermediates: 'Pro vytvoření polotovaru je potřeba nejprve přidat suroviny.',
  emptyRecipes: 'Nejdříve vytvořte polotovary nebo suroviny pro výrobu receptury.',
  emptyOrders: 'Dosud nebyla založena žádná zakázka.',
  emptySuppliers: 'Zatím nemáte evidované dodavatele – doplňte je k surovinám.',
  suppliersIntro: 'Přehled dodavatelů podle evidovaných surovin a jejich cen.',
  addMaterial: 'Přidat surovinu',
  addIntermediate: 'Vytvořit polotovar',
  addRecipe: 'Sestavit recepturu',
  addOrder: 'Založit zakázku',
  composition: 'Složení',
  analytics: 'Rychlý přehled',
  delete: 'Smazat',
  customer: 'Zákazník',
  recipeLabel: 'Receptura',
  dueDate: 'Termín výroby',
  quantity: 'Množství',
  status: 'Stav',
};
